name: Run Tests

on:
    pull_request:
        branches: [main, "major/**"]
    push:
        branches: [main]

jobs:
    run-tests:
        runs-on: ubuntu-latest # Cannot find module @rollup/rollup-linux-x64-gnu. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Setup .NET
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: "10.0.x"

            - name: Setup Node.js and NPM
              uses: actions/setup-node@v5
              with:
                  node-version: "22"
                  cache: "npm"

            - name: Setup python and uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

            - name: Restore .NET tools
              run: dotnet tool restore

            - name: Log versions
              run: |
                  dotnet --version
                  node --version
                  npm --version
                  uv --version

            - name: Install JavaScript dependencies
              run: npm install

            - name: Install uv dependencies
              run: uv sync

            - name: run tests
              run: dotnet run --project ./build/Build.fsproj runtests
